hoge-apache:
  build: apache
  ports:
    - "8080:80"
  container_name: hoge-apache
  volumes:
    - ./var/apache/hoge:/user/local/apache2/htdocs/hoge

hoge-java:
  build: java
  ports:
    - "8001:8001"
  container_name: hoge-java
  links:
    - hoge-apache
